#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
