spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
#      username: root
#      password: 12345678
#      driver-class-name: com.mysql.cj.jdbc.Driver



  application:
    name: spring-boot-01
  profiles:
    active: '@profileActive@'


server:
  port: 8001
  servlet:
    context-path: /01


management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  server:
    port: 2${server.port}
  metrics:
    tags:
      application: ${spring.application.name}


mybatis:
  mapper-locations: classpath:mapper/*.xml


