spring:
  application:
    name: spring-boot-01
  profiles:
    active: '@profileActive@'
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 监控后台地址： http://127.0.0.1:{server.port}/{server.servlet.context-path}/druid
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: cn.wang.*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 10
        max-active: 10
        max-idle: 10









server:
  port: 8001
  servlet:
    context-path: /01


management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  server:
    port: 2${server.port}
  metrics:
    tags:
      application: ${spring.application.name}


mybatis:
  mapper-locations: classpath:mapper/*.xml


