spring:
  application:
    name: spring-boot-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1


server:
  port: 8888
  servlet:
    context-path: /


mybatis:
  mapper-locations: classpath:mapper/*.xml



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000